"""Agrega campo tiene_discapacidad

Revision ID: 8dea7a5da153
Revises: 
Create Date: 2025-07-10 16:13:46.575981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dea7a5da153'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inclusiones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tiene_discapacidad', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inclusiones', schema=None) as batch_op:
        batch_op.drop_column('tiene_discapacidad')

    # ### end Alembic commands ###
